name: Build & Release Skript-Oraxen

on:
  push:
    tags:
      - 'v*' # Déclenche le workflow sur un tag commençant par "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build plugin with ShadowJar
        run: ./gradlew shadowJar

      - name: Rename JAR with version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mkdir output
          JAR_PATH=$(find build/libs -name '*-all.jar' | head -n 1)
          cp "$JAR_PATH" "output/skript-oraxen-${VERSION}.jar"
      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/skript-oraxen-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
