name: Build & Release Skript-Oraxen

on:
  push:
    tags:
      - 'v*' # Ex : v1.0, v1.1.2 => déclenche le workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build plugin with ShadowJar
        run: ./gradlew shadowJar

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/skript-oraxen-*-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
